name: Cleanup Old Artifacts

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1:00 AM UTC

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write

    steps:
      - name: Cleanup Old Artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '7 days'
          skip-tags: true
          skip-recent: 2
