name: Cleanup Old Artifacts

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1:00 AM UTC

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: c-hive/gha-remove-artifacts@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-latest: 2

